### ISSUE TITLE
Is it possible to remove "xcopy" command from .csproj files?

### ISSUE THREAD

**Issue by twi123** [bitai-cs/LDAPHelper#2]
https://github.com/bitai-cs/LDAPHelper/blob/bd78e287358283c076b6f7ee8d02c9f52bc237d7/src/Bitai.LDAPHelper/Bitai.LDAPHelper.csproj#L51
and
https://github.com/bitai-cs/LDAPHelper/blob/bd78e287358283c076b6f7ee8d02c9f52bc237d7/src/Bitai.LDAPHelper.DTO/Bitai.LDAPHelper.DTO.csproj#L37

and replace it with something like
```
...
<Copy SourceFiles="$(TargetDir)*.*" DestinationFolder="$(ProjectDir)..\..\..\_bin\netstandard2.0\LdapHelperDTO\" SkipUnchangedFiles="true" />
...
```
for other OSes compatibility?

For example, it causes an error when trying to build under Linux (.netcore)...

**Comment by bitai-cs** [comment]
Hi @twi123 

Ok, I removed them in both cases. They were already unnecessary.

Thanks for noticing.

**Comment by twi123** [comment]
Thank you!!!
Is it possible to release a new NuGet package with these changes? )
Thnx!

**Comment by bitai-cs** [comment]
Hi @twi123 

A Nuget package update has already been released.
